// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Villa_Api.Data;

#nullable disable

namespace Villa_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231203131043_AddVillaNumbertable")]
    partial class AddVillaNumbertable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Villa_Api.Model.Villa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("rate")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CreatedDate = new DateTime(2023, 12, 3, 18, 40, 43, 387, DateTimeKind.Local).AddTicks(9810),
                            Occupancy = 10000,
                            Sqft = 10,
                            UpdatedDate = new DateTime(2023, 12, 3, 18, 40, 43, 387, DateTimeKind.Local).AddTicks(9850),
                            name = "Ashok",
                            rate = 20.0
                        },
                        new
                        {
                            id = 2,
                            CreatedDate = new DateTime(2023, 12, 3, 18, 40, 43, 387, DateTimeKind.Local).AddTicks(9850),
                            Occupancy = 10000,
                            Sqft = 10,
                            UpdatedDate = new DateTime(2023, 12, 3, 18, 40, 43, 387, DateTimeKind.Local).AddTicks(9850),
                            name = "Kumar",
                            rate = 20.0
                        });
                });

            modelBuilder.Entity("Villa_Api.Model.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VillaNo");

                    b.ToTable("VillaNumber");

                    b.HasData(
                        new
                        {
                            VillaNo = 1,
                            CreatedDate = new DateTime(2023, 12, 3, 18, 40, 43, 387, DateTimeKind.Local).AddTicks(9920),
                            SpecialDetails = "Blue",
                            UpdatedDate = new DateTime(2023, 12, 3, 18, 40, 43, 387, DateTimeKind.Local).AddTicks(9920)
                        },
                        new
                        {
                            VillaNo = 2,
                            CreatedDate = new DateTime(2023, 12, 3, 18, 40, 43, 387, DateTimeKind.Local).AddTicks(9920),
                            SpecialDetails = "Orange",
                            UpdatedDate = new DateTime(2023, 12, 3, 18, 40, 43, 387, DateTimeKind.Local).AddTicks(9920)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
